shadow_maps_x3d_slides.pdf: shadow_maps_x3d_slides.tex
	pdflatex -file-line-error -interaction=nonstopmode shadow_maps_x3d_slides.tex
	pdflatex -file-line-error -interaction=nonstopmode shadow_maps_x3d_slides.tex

.PHONY: 1
1:
	pdflatex -file-line-error -interaction=nonstopmode shadow_maps_x3d_slides.tex

.PHONY: clean
clean:
	rm -f shadow_maps_x3d_slides.pdf \
	      shadow_maps_x3d_slides.aux \
	      shadow_maps_x3d_slides.log \
	      shadow_maps_x3d_slides.out \
	      shadow_maps_x3d_slides.dvi \
	      shadow_maps_x3d_slides.ps \
	      shadow_maps_x3d_slides.nav \
	      shadow_maps_x3d_slides.toc \
	      shadow_maps_x3d_slides.snm \
	      shadow_maps_x3d_slides.vrb
