mytitlepage.xsl: mytitlepage.xml
	xsltproc -output mytitlepage.xsl \
	  /usr/share/sgml/docbook/stylesheet/xsl/nwalsh/template/titlepage.xsl \
	  mytitlepage.xml

.PHONY: clean
clean:
	rm -f mytitlepage.xsl